apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: goapp
    image: sihanding/webapp
    volumeMounts:
    - name: foo
      mountPath: "/app/"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: certificate-by-chaos-issuer
      items:
      - key: tls.crt
        path: localhost.crt
      - key: tls.key
        path: localhost.key