apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-server
spec:
  secretName: mysql-server-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
  commonName: MySQL server
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io