apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
spec:
  tls:
  - hosts:
    - example.example.com
    secretName: certificate-by-chaos-issuer
  rules:
  - host: example.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 8888

