apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-server
spec:
  secretName: certificate-by-chaos-issuer
  commonName: MySQL server
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: example-issuer
    kind: ChaosIssuer
    group: self-signed-issuer.chaos.ch